services:
  webgis:
    build: .
    container_name: urban_webgis
    restart: always
    ports:
      - "8081:5000"  # å°†æœåŠ¡å™¨çš„ 8081 ç«¯å£æ˜ å°„åˆ°å®¹å™¨çš„ 5000 ç«¯å£
    volumes:
      # ğŸ”¥ å…³é”®ï¼šæŠŠæœåŠ¡å™¨ä¸Šçš„ data æ–‡ä»¶å¤¹æŒ‚è½½è¿›å»
      # è¿™æ ·ä½ ä¸éœ€è¦æŠŠ 150MB çš„æ•°æ®æ‰“åŒ…è¿›é•œåƒï¼Œä¸”æ›´æ–°æ•°æ®åªéœ€æ›¿æ¢æœåŠ¡å™¨æ–‡ä»¶
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1 # å¼ºåˆ¶å®æ—¶è¾“å‡ºæ—¥å¿—